{{config(materialized = "view")}}

WITH ORDERS_BY_DATE AS (
    SELECT O_ORDERDATE
    , SUM(O_TOTALPRICE) AS ORDERS_BY_DATE
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS
    GROUP BY O_ORDERDATE
)

SELECT O_ORDERDATE
, SUM(ORDERS_BY_DATE)
    OVER
        (ORDER BY O_ORDERDATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMULATIVE_ORDERS_BY_DATE
FROM ORDERS_BY_DATE
ORDER BY O_ORDERDATE